name: Terraform Provider Acceptance Tests Lite
on:
  #Every day at 08:00 UTC
  schedule:
    - cron: '0 8 * * *'
  push:
permissions:
  # Permission for checking out code
  contents: read
jobs:
  # Lite acceptance tests run on zerocloud provider only, which makes them really fast,
  # but with limited coverage
  acceptance_lite:
    name: Acceptance Tests Lite (Terraform ${{ matrix.terraform-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        terraform-version:
          - '1.2.*'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.19'
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform-version }}
          terraform_wrapper: false
      - run: make testacc TESTARGS="-run='TestAccResourceVmcSddcRequiredFieldsOnlyZerocloud|TestAccResourceVmcSddcZerocloud|TestAccResourceVmcClusterZerocloud|TestAccResourceVmcClusterRequiredFieldsZerocloud|TestAccResourceVmcSiteRecoveryZerocloud|TestAccResourceVmcSrmNodeZerocloud|TestAccResourceVmcMultipleSrmNodesZerocloud|TestAccDataSourceVmcCustomerSubnetsBasic|TestAccDataSourceVmcCustomerSubnetsOnlyRequiredProperties|TestAccDataSourceVmcConnectedAccountsBasic|TestAccDataSourceVmcOrgBasic|TestAccDataSourceVmcSddcBasic|TestAccResourceSddcGroupZerocloud' -parallel 4"
        env:
          TF_ACC: '1'
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          AWS_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_NUMBER }}
          CSP_URL: ${{ secrets.CSP_URL }}
          ORG_DISPLAY_NAME: ${{ secrets.ORG_DISPLAY_NAME }}
          ORG_ID: ${{ secrets.ORG_ID }}
          TEST_SDDC_ID: ${{ secrets.TEST_SDDC_ID }}
          SDDC_GROUP_TEST_SDDC_1_ID: ${{ secrets.SDDC_GROUP_TEST_SDDC_1_ID }}
          SDDC_GROUP_TEST_SDDC_2_ID: ${{ secrets.SDDC_GROUP_TEST_SDDC_2_ID }}
          TEST_SDDC_NAME: ${{ secrets.TEST_SDDC_NAME }}
          VMC_URL: ${{ secrets.VMC_URL }}
