name: Spectral Scan

on:
  push:
    branches: [ main ]

env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Install and Run Spectral CI
        uses: spectralops/spectral-github-action@e5c74cf93c5dfc163527851a1e907f4e7d956d4e # v5
        with:
          spectral-dsn: ${{ env.SPECTRAL_DSN }}
          spectral-args: scan --ok --include-tags base,audit,iac --asset-mapping "VMware Github"
